apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: charts/external-secrets
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    targetRevision: main
    helm:
      releaseName: external-secrets
      valuesFiles:
        - values-prod.yaml
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
