apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-server
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: jenkins
  project: default
  source:
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    targetRevision: main
    path: charts/jenkins
    helm:
      releaseName: jenkins-server
      valuesFiles:
        - values.yaml
        - values-prod.yaml
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: jenkins-server
      namespace: jenkins
      jsonPointers:
        - /spec
