apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    path: charts/fastapi-ml
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    name: in-cluster
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
